import { Navbar } from "@/components/navbar";
import "./globals.css";
import { Roboto, Roboto_Mono } from "next/font/google";
import StyledComponentsRegistry from "@/lib/registry";
import styles from "./page.module.css";

const roboto = Roboto({ weight: ["400", "500", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <StyledComponentsRegistry>
          <div className={styles.pageBackground}>
            <Navbar />
            {children}
          </div>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
